#!/usr/bin/env python3
import json
import os
import urllib.request
from datetime import date, datetime, timedelta, timezone
from pathlib import Path

USER = os.getenv("PROFILE_USER", "aproto9787")
TOKEN = os.environ["GH_TOKEN"]
OUT = Path("assets")
OUT.mkdir(exist_ok=True)

QUERY = r'''
query($login: String!, $from: DateTime!, $to: DateTime!) {
  user(login: $login) {
    contributionsCollection(from: $from, to: $to) {
      contributionCalendar {
        totalContributions
        weeks {
          contributionDays {
            date
            contributionCount
          }
        }
      }
    }
    repositories(first: 100, ownerAffiliations: OWNER, privacy: PUBLIC) {
      totalCount
      nodes { stargazerCount }
    }
  }
}
'''


def graphql(query, variables):
    body = json.dumps({"query": query, "variables": variables}).encode()
    req = urllib.request.Request(
        "https://api.github.com/graphql",
        data=body,
        headers={
            "Authorization": f"Bearer {TOKEN}",
            "Content-Type": "application/json",
            "User-Agent": "aproto9787-profile-stats",
        },
    )
    with urllib.request.urlopen(req, timeout=30) as resp:
        payload = json.load(resp)
    if payload.get("errors"):
        raise RuntimeError(payload["errors"])
    return payload["data"]


def esc(value):
    return str(value).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def streaks(days):
    counts = {date.fromisoformat(d["date"]): d["contributionCount"] for d in days}
    today = datetime.now(timezone.utc).date()
    start = today if counts.get(today, 0) > 0 else today - timedelta(days=1)
    current = 0
    d = start
    while counts.get(d, 0) > 0:
        current += 1
        d -= timedelta(days=1)

    longest = run = 0
    for d in sorted(counts):
        if counts[d] > 0:
            run += 1
            longest = max(longest, run)
        else:
            run = 0
    return current, longest


def stats_svg(total, repos, stars, current, longest):
    items = [
        ("Contributions", total),
        ("Public Repos", repos),
        ("Stars", stars),
        ("Current Streak", current),
        ("Longest Streak", longest),
    ]
    xs = [80, 215, 350, 485, 620]
    parts = [
        '<svg xmlns="http://www.w3.org/2000/svg" width="700" height="180" viewBox="0 0 700 180">',
        '<rect width="700" height="180" rx="14" fill="#0d1117" stroke="#30363d"/>',
        '<text x="32" y="40" fill="#73daca" font-family="Segoe UI,Arial,sans-serif" font-size="20" font-weight="700">GitHub Activity</text>',
        '<text x="32" y="62" fill="#6e7681" font-family="Segoe UI,Arial,sans-serif" font-size="11">rolling 365 days · generated by GitHub Actions</text>',
    ]
    for x, (label, value) in zip(xs, items):
        parts.append(f'<text x="{x}" y="112" text-anchor="middle" fill="#c9d1d9" font-family="Segoe UI,Arial,sans-serif" font-size="24" font-weight="700">{esc(value)}</text>')
        parts.append(f'<text x="{x}" y="136" text-anchor="middle" fill="#8b949e" font-family="Segoe UI,Arial,sans-serif" font-size="11">{esc(label)}</text>')
    parts.append('</svg>')
    return "".join(parts)


def graph_svg(weeks):
    cell, gap = 11, 3
    left, top = 34, 54
    width, height = 900, 180
    all_counts = [d["contributionCount"] for w in weeks for d in w["contributionDays"]]
    max_count = max(all_counts or [0])

    def color(count):
        if count <= 0:
            return "#161b22"
        ratio = count / max_count if max_count else 0
        if ratio <= 0.25:
            return "#0e4429"
        if ratio <= 0.5:
            return "#006d32"
        if ratio <= 0.75:
            return "#26a641"
        return "#39d353"

    parts = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}">',
        f'<rect width="{width}" height="{height}" rx="14" fill="#0d1117" stroke="#30363d"/>',
        '<text x="28" y="30" fill="#73daca" font-family="Segoe UI,Arial,sans-serif" font-size="17" font-weight="700">Contribution Activity</text>',
    ]
    for wi, week in enumerate(weeks[-53:]):
        for di, day in enumerate(week["contributionDays"]):
            x = left + wi * (cell + gap)
            y = top + di * (cell + gap)
            count = day["contributionCount"]
            parts.append(f'<rect x="{x}" y="{y}" width="{cell}" height="{cell}" rx="2" fill="{color(count)}"><title>{esc(day["date"])}: {count} contributions</title></rect>')
    parts.append('<text x="28" y="160" fill="#6e7681" font-family="Segoe UI,Arial,sans-serif" font-size="10">GitHub public contribution calendar · refreshed daily</text>')
    parts.append('</svg>')
    return "".join(parts)


def main():
    now = datetime.now(timezone.utc)
    start = now - timedelta(days=364)
    data = graphql(
        QUERY,
        {
            "login": USER,
            "from": start.strftime("%Y-%m-%dT00:00:00Z"),
            "to": now.strftime("%Y-%m-%dT23:59:59Z"),
        },
    )["user"]

    calendar = data["contributionsCollection"]["contributionCalendar"]
    weeks = calendar["weeks"]
    days = [d for w in weeks for d in w["contributionDays"]]
    current, longest = streaks(days)
    repos = data["repositories"]
    stars = sum(r["stargazerCount"] for r in repos["nodes"])

    (OUT / "github-stats.svg").write_text(
        stats_svg(calendar["totalContributions"], repos["totalCount"], stars, current, longest),
        encoding="utf-8",
    )
    (OUT / "contribution-graph.svg").write_text(graph_svg(weeks), encoding="utf-8")


if __name__ == "__main__":
    main()
